/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author tuannnh
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    ArrayList<String> numberList;
    List<JButton> listOf3x3;
    List<JButton> listOf4x4;
    boolean running;
    long startTime;
    long currentTime;
    long elsapedTime;
    long minutes;
    long seconds;
    int moves;
    Thread t;

    public MainForm() {
        initComponents();
        //List for randomize
        numberList = new ArrayList<>();

        //List to contain buttons
        listOf3x3 = new ArrayList<>();
        listOf3x3.add(btn31);
        listOf3x3.add(btn32);
        listOf3x3.add(btn33);
        listOf3x3.add(btn34);
        listOf3x3.add(btn35);
        listOf3x3.add(btn36);
        listOf3x3.add(btn37);
        listOf3x3.add(btn38);
        listOf3x3.add(btn39);

        listOf4x4 = new ArrayList<>();
        listOf4x4.add(btn41);
        listOf4x4.add(btn42);
        listOf4x4.add(btn43);
        listOf4x4.add(btn44);
        listOf4x4.add(btn45);
        listOf4x4.add(btn46);
        listOf4x4.add(btn47);
        listOf4x4.add(btn48);
        listOf4x4.add(btn49);
        listOf4x4.add(btn410);
        listOf4x4.add(btn411);
        listOf4x4.add(btn412);
        listOf4x4.add(btn413);
        listOf4x4.add(btn414);
        listOf4x4.add(btn415);
        listOf4x4.add(btn416);

        t = new Thread() {
            public void run() {
                while (true) {
                    try {
                        if(running){
                            currentTime = System.currentTimeMillis();
                        elsapedTime = currentTime - startTime;
                        minutes = (elsapedTime / 1000) / 60;
                        seconds = (elsapedTime / 1000) % 60;
                        lblTime.setText(String.format("%02d:%02d", minutes, seconds));
                        sleep(1000);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        };
        t.start();
        btnNewGameActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Puzzle16Panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ButtonMap1 = new javax.swing.JPanel();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn48 = new javax.swing.JButton();
        btn49 = new javax.swing.JButton();
        btn410 = new javax.swing.JButton();
        btn411 = new javax.swing.JButton();
        btn412 = new javax.swing.JButton();
        btn413 = new javax.swing.JButton();
        btn414 = new javax.swing.JButton();
        btn415 = new javax.swing.JButton();
        btn416 = new javax.swing.JButton();
        Puzzle9Panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ButtonMap = new javax.swing.JPanel();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        ControlPanel = new javax.swing.JPanel();
        lblMoveCount = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbboxSize = new javax.swing.JComboBox<>();
        btnNewGame = new javax.swing.JButton();
        btnCheat = new javax.swing.JButton();
        lblMove = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 550));

        Puzzle16Panel.setPreferredSize(new java.awt.Dimension(300, 300));

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Puzzle16Panel.add(jPanel2);

        ButtonMap1.setPreferredSize(new java.awt.Dimension(250, 250));
        ButtonMap1.setLayout(new java.awt.GridLayout(4, 4, 20, 20));

        btn41.setText("1");
        btn41.setPreferredSize(new java.awt.Dimension(60, 60));
        btn41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn41ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn41);

        btn42.setText("2");
        btn42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn42ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn42);

        btn43.setText("3");
        btn43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn43ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn43);

        btn44.setText("4");
        btn44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn44ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn44);

        btn45.setText("5");
        btn45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn45ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn45);

        btn46.setText("6");
        btn46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn46ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn46);

        btn47.setText("7");
        btn47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn47ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn47);

        btn48.setText("8");
        btn48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn48ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn48);

        btn49.setText("9");
        btn49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn49ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn49);

        btn410.setText("10");
        btn410.setPreferredSize(new java.awt.Dimension(60, 60));
        btn410.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn410ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn410);

        btn411.setText("11");
        btn411.setPreferredSize(new java.awt.Dimension(60, 60));
        btn411.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn411ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn411);

        btn412.setText("12");
        btn412.setPreferredSize(new java.awt.Dimension(60, 60));
        btn412.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn412ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn412);

        btn413.setText("13");
        btn413.setPreferredSize(new java.awt.Dimension(60, 60));
        btn413.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn413ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn413);

        btn414.setText("14");
        btn414.setPreferredSize(new java.awt.Dimension(60, 60));
        btn414.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn414ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn414);

        btn415.setText("15");
        btn415.setPreferredSize(new java.awt.Dimension(60, 60));
        btn415.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn415ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn415);

        btn416.setPreferredSize(new java.awt.Dimension(60, 60));
        btn416.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn416ActionPerformed(evt);
            }
        });
        ButtonMap1.add(btn416);

        Puzzle16Panel.add(ButtonMap1);

        getContentPane().add(Puzzle16Panel, java.awt.BorderLayout.NORTH);

        Puzzle9Panel.setPreferredSize(new java.awt.Dimension(300, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Puzzle9Panel.add(jPanel1);

        ButtonMap.setPreferredSize(new java.awt.Dimension(250, 250));
        ButtonMap.setLayout(new java.awt.GridLayout(3, 3, 20, 20));

        btn31.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn31.setText("1");
        btn31.setPreferredSize(new java.awt.Dimension(60, 60));
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn31);

        btn32.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn32.setText("2");
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn32);

        btn33.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn33.setText("3");
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn33);

        btn34.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn34.setText("4");
        btn34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn34ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn34);

        btn35.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn35.setText("5");
        btn35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn35ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn35);

        btn36.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn36.setText("6");
        btn36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn36ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn36);

        btn37.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn37.setText("7");
        btn37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn37ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn37);

        btn38.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn38.setText("8");
        btn38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn38ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn38);

        btn39.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btn39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn39ActionPerformed(evt);
            }
        });
        ButtonMap.add(btn39);

        Puzzle9Panel.add(ButtonMap);

        getContentPane().add(Puzzle9Panel, java.awt.BorderLayout.NORTH);

        ControlPanel.setPreferredSize(new java.awt.Dimension(300, 250));

        lblMoveCount.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        lblMoveCount.setText("Move Count:");
        lblMoveCount.setPreferredSize(new java.awt.Dimension(200, 30));

        jlabel.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jlabel.setText("Elapsed:");
        jlabel.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Size:");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 30));

        cbboxSize.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        cbboxSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x3", "4x4" }));
        cbboxSize.setPreferredSize(new java.awt.Dimension(150, 30));
        cbboxSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbboxSizeActionPerformed(evt);
            }
        });

        btnNewGame.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        btnNewGame.setText("New Game");
        btnNewGame.setPreferredSize(new java.awt.Dimension(150, 50));
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnCheat.setText("Cheat");
        btnCheat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheatActionPerformed(evt);
            }
        });

        lblMove.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        lblMove.setText("0");

        lblTime.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 15)); // NOI18N
        lblTime.setText("00:00");

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbboxSize, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime))
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addComponent(lblMoveCount, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMove)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoveCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMove))
                .addGap(5, 5, 5)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbboxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCheat)
                .addContainerGap())
        );

        getContentPane().add(ControlPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        //3x3 Board
        moves = 0;
        lblMove.setText(""+moves);
        startTime = System.currentTimeMillis();
        if (cbboxSize.getSelectedIndex() == 0) {
            numberList.clear();
            for (int i = 1; i < 9; i++) {
                numberList.add("" + i);
            }
            //Add 1 blank button
            numberList.add("");

            //Random number for a new game
            Collections.shuffle(numberList);

            for (int i = 0; i < 9; i++) {
                listOf3x3.get(i).setText(numberList.get(i));
            }

            for (JButton button : listOf3x3) {
                button.setEnabled(true);
            }
        } //4x4 Board
        else {
            numberList.clear();
            for (int i = 1; i < 16; i++) {
                numberList.add("" + i);
            }
            numberList.add("");
            Collections.shuffle(numberList);

            for (int i = 0; i < 16; i++) {
                listOf4x4.get(i).setText(numberList.get(i));
            }
            for (JButton button : listOf4x4) {
                button.setEnabled(true);
            }
        }
        running = true;
       
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void cbboxSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbboxSizeActionPerformed
        // TODO add your handling code here:
        if (cbboxSize.getSelectedIndex() == 0) {
            Puzzle9Panel.setVisible(true);
            Puzzle16Panel.setVisible(false);
            getContentPane().add(Puzzle16Panel, java.awt.BorderLayout.NORTH);
            getContentPane().add(Puzzle9Panel, java.awt.BorderLayout.CENTER);
        } else {
            Puzzle9Panel.setVisible(false);
            getContentPane().add(Puzzle16Panel, java.awt.BorderLayout.CENTER);
            getContentPane().add(Puzzle9Panel, java.awt.BorderLayout.NORTH);
            Puzzle16Panel.setVisible(true);
        }
        btnNewGameActionPerformed(null);

    }//GEN-LAST:event_cbboxSizeActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        // TODO add your handling code here:
        if(btn32.getText().equalsIgnoreCase("")){
            btn32.setText(btn31.getText());
            btn31.setText("");
            moves++;
        }
         if(btn34.getText().equalsIgnoreCase("")){
            btn34.setText(btn31.getText());
            btn31.setText("");
                        moves++;

        }
        if(checkWinCondition()){
            congratulate();
        }
    }//GEN-LAST:event_btn31ActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        // TODO add your handling code here:
        if (btn31.getText().equals("")) {
            btn31.setText(btn32.getText());
            btn32.setText("");
            moves++;
        }
        if (btn33.getText().equals("")) {
            btn33.setText(btn32.getText());
            btn32.setText("");
            moves++;
        }
        if (btn35.getText().equals("")) {
            btn35.setText(btn32.getText());
            btn32.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        // TODO add your handling code here:
        if (btn32.getText().equals("")) {
            btn32.setText(btn33.getText());
            btn33.setText("");
            moves++;
        } else if (btn36.getText().equals("")) {
            btn36.setText(btn33.getText());
            btn33.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn33ActionPerformed

    private void btn34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn34ActionPerformed
        // TODO add your handling code here:
        if (btn31.getText().equals("")) {
            btn31.setText(btn34.getText());
            btn34.setText("");
            moves++;
        }
        if (btn35.getText().equals("")) {
            btn35.setText(btn34.getText());
            btn34.setText("");
            moves++;
        }
        if (btn37.getText().equals("")) {
            btn37.setText(btn34.getText());
            btn34.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn34ActionPerformed

    private void btn35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn35ActionPerformed
        // TODO add your handling code here:
        if (btn32.getText().equals("")) {
            btn32.setText(btn35.getText());
            btn35.setText("");
            moves++;
        }
        if (btn34.getText().equals("")) {
            btn34.setText(btn35.getText());
            btn35.setText("");
            moves++;
        }
        if (btn36.getText().equals("")) {
            btn36.setText(btn35.getText());
            btn35.setText("");
            moves++;
        }
        if (btn38.getText().equals("")) {
            btn38.setText(btn35.getText());
            btn35.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn35ActionPerformed

    private void btn36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn36ActionPerformed
        // TODO add your handling code here:
        if (btn35.getText().equals("")) {
            btn35.setText(btn36.getText());
            btn36.setText("");
            moves++;
        }
        if (btn39.getText().equals("")) {
            btn39.setText(btn36.getText());
            btn36.setText("");
            moves++;
        }
        if (btn33.getText().equals("")) {
            btn33.setText(btn36.getText());
            btn36.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn36ActionPerformed

    private void btn37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn37ActionPerformed
        // TODO add your handling code here:
        if (btn34.getText().equals("")) {
            btn34.setText(btn37.getText());
            btn37.setText("");
            moves++;
        } else if (btn38.getText().equals("")) {
            btn38.setText(btn37.getText());
            btn37.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn37ActionPerformed

    private void btn38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn38ActionPerformed
        // TODO add your handling code here:
        if (btn37.getText().equals("")) {
            btn37.setText(btn38.getText());
            btn38.setText("");
            moves++;
        }
        if (btn35.getText().equals("")) {
            btn35.setText(btn38.getText());
            btn38.setText("");
            moves++;
        }
        if (btn39.getText().equals("")) {
            btn39.setText(btn38.getText());
            btn38.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn38ActionPerformed

    private void btn39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn39ActionPerformed
        // TODO add your handling code here:
        if (btn36.getText().equals("")) {
            btn36.setText(btn39.getText());
            btn39.setText("");
            moves++;
        } else if (btn38.getText().equals("")) {
            btn38.setText(btn39.getText());
            btn39.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn39ActionPerformed

    private void btnCheatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheatActionPerformed
        // TODO add your handling code here:
        if (cbboxSize.getSelectedIndex() == 0) {
            numberList.clear();
            for (int i = 1; i < 9; i++) {
                numberList.add("" + i);
            }
            //Add 1 blank button
            numberList.add("");

            for (int i = 0; i < 9; i++) {
                listOf3x3.get(i).setText(numberList.get(i));
            }

        } //4x4 Board
        else {
            numberList.clear();
            for (int i = 1; i < 16; i++) {
                numberList.add("" + i);
            }
            numberList.add("");

            for (int i = 0; i < 16; i++) {
                listOf4x4.get(i).setText(numberList.get(i));
            }
        }
    }//GEN-LAST:event_btnCheatActionPerformed

    private void btn41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn41ActionPerformed
        // TODO add your handling code here:
        if (btn42.getText().equals("")) {
            btn42.setText(btn41.getText());
            btn41.setText("");
            moves++;
        }
        if (btn45.getText().equals("")) {
            btn45.setText(btn41.getText());
            btn41.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn41ActionPerformed

    private void btn42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn42ActionPerformed
        // TODO add your handling code here:
        if (btn41.getText().equals("")) {
            btn41.setText(btn42.getText());
            btn42.setText("");
            moves++;
        }
        if (btn43.getText().equals("")) {
            btn43.setText(btn42.getText());
            btn42.setText("");
            moves++;
        }
        if (btn46.getText().equals("")) {
            btn46.setText(btn42.getText());
            btn42.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn42ActionPerformed

    private void btn43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn43ActionPerformed
        // TODO add your handling code here:
        if (btn42.getText().equals("")) {
            btn42.setText(btn43.getText());
            btn43.setText("");
            moves++;
        }
        if (btn44.getText().equals("")) {
            btn44.setText(btn43.getText());
            btn43.setText("");
            moves++;
        }
        if (btn47.getText().equals("")) {
            btn47.setText(btn43.getText());
            btn43.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn43ActionPerformed

    private void btn44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn44ActionPerformed
        // TODO add your handling code here:
        if (btn43.getText().equals("")) {
            btn43.setText(btn44.getText());
            btn44.setText("");
            moves++;
        }
        if (btn48.getText().equals("")) {
            btn48.setText(btn44.getText());
            btn44.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn44ActionPerformed

    private void btn45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn45ActionPerformed
        // TODO add your handling code here:
        if (btn41.getText().equals("")) {
            btn41.setText(btn45.getText());
            btn45.setText("");
            moves++;
        }
        if (btn46.getText().equals("")) {
            btn46.setText(btn45.getText());
            btn45.setText("");
            moves++;
        }
        if (btn49.getText().equals("")) {
            btn49.setText(btn45.getText());
            btn45.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn45ActionPerformed

    private void btn46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn46ActionPerformed
        // TODO add your handling code here:
        if (btn42.getText().equals("")) {
            btn42.setText(btn46.getText());
            btn46.setText("");
            moves++;
        }
        if (btn45.getText().equals("")) {
            btn45.setText(btn46.getText());
            btn46.setText("");
            moves++;
        }
        if (btn47.getText().equals("")) {
            btn47.setText(btn46.getText());
            btn46.setText("");
            moves++;
        }
        if (btn410.getText().equals("")) {
            btn410.setText(btn46.getText());
            btn46.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn46ActionPerformed

    private void btn47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn47ActionPerformed
        // TODO add your handling code here:
        if (btn43.getText().equals("")) {
            btn43.setText(btn47.getText());
            btn47.setText("");
            moves++;
        }
        if (btn46.getText().equals("")) {
            btn46.setText(btn47.getText());
            btn47.setText("");
            moves++;
        }
        if (btn48.getText().equals("")) {
            btn48.setText(btn47.getText());
            btn47.setText("");
            moves++;
        }
        if (btn411.getText().equals("")) {
            btn411.setText(btn47.getText());
            btn47.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn47ActionPerformed

    private void btn48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn48ActionPerformed
        // TODO add your handling code here:
        if (btn44.getText().equals("")) {
            btn44.setText(btn48.getText());
            btn48.setText("");
            moves++;
        }
        if (btn47.getText().equals("")) {
            btn47.setText(btn48.getText());
            btn48.setText("");
            moves++;
        }
        if (btn412.getText().equals("")) {
            btn412.setText(btn48.getText());
            btn48.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn48ActionPerformed

    private void btn49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn49ActionPerformed
        // TODO add your handling code here:
        if (btn45.getText().equals("")) {
            btn45.setText(btn49.getText());
            btn49.setText("");
            moves++;
        }
        if (btn410.getText().equals("")) {
            btn410.setText(btn49.getText());
            btn49.setText("");
            moves++;
        }
        if (btn413.getText().equals("")) {
            btn413.setText(btn49.getText());
            btn49.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn49ActionPerformed

    private void btn410ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn410ActionPerformed
        // TODO add your handling code here:
        if (btn46.getText().equals("")) {
            btn46.setText(btn410.getText());
            btn410.setText("");
            moves++;
        }
        if (btn49.getText().equals("")) {
            btn49.setText(btn410.getText());
            btn410.setText("");
            moves++;
        }
        if (btn411.getText().equals("")) {
            btn411.setText(btn410.getText());
            btn410.setText("");
            moves++;
        }
        if (btn414.getText().equals("")) {
            btn414.setText(btn410.getText());
            btn410.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn410ActionPerformed

    private void btn411ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn411ActionPerformed
        // TODO add your handling code here:
        if (btn47.getText().equals("")) {
            btn47.setText(btn411.getText());
            btn411.setText("");
            moves++;
        }
        if (btn410.getText().equals("")) {
            btn410.setText(btn411.getText());
            btn411.setText("");
            moves++;
        }
        if (btn412.getText().equals("")) {
            btn412.setText(btn411.getText());
            btn411.setText("");
            moves++;
        }
        if (btn415.getText().equals("")) {
            btn415.setText(btn411.getText());
            btn411.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn411ActionPerformed

    private void btn412ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn412ActionPerformed
        // TODO add your handling code here:
        if (btn48.getText().equals("")) {
            btn48.setText(btn412.getText());
            btn412.setText("");
            moves++;
        }
        if (btn411.getText().equals("")) {
            btn411.setText(btn412.getText());
            btn412.setText("");
            moves++;
        }
        if (btn416.getText().equals("")) {
            btn416.setText(btn412.getText());
            btn412.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn412ActionPerformed

    private void btn413ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn413ActionPerformed
        // TODO add your handling code here:
        if (btn49.getText().equals("")) {
            btn49.setText(btn413.getText());
            btn413.setText("");
            moves++;
        }
        if (btn414.getText().equals("")) {
            btn414.setText(btn413.getText());
            btn413.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn413ActionPerformed

    private void btn414ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn414ActionPerformed
        // TODO add your handling code here:
        if (btn410.getText().equals("")) {
            btn410.setText(btn414.getText());
            btn414.setText("");
            moves++;
        }
        if (btn413.getText().equals("")) {
            btn413.setText(btn414.getText());
            btn414.setText("");
            moves++;
        }
        if (btn415.getText().equals("")) {
            btn415.setText(btn414.getText());
            btn414.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn414ActionPerformed

    private void btn415ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn415ActionPerformed
        // TODO add your handling code here:
        if (btn411.getText().equals("")) {
            btn411.setText(btn415.getText());
            btn415.setText("");
            moves++;
        }
        if (btn414.getText().equals("")) {
            btn414.setText(btn415.getText());
            btn415.setText("");
            moves++;
        }
        if (btn416.getText().equals("")) {
            btn416.setText(btn415.getText());
            btn415.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn415ActionPerformed

    private void btn416ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn416ActionPerformed
        // TODO add your handling code here:
        if (btn412.getText().equals("")) {
            btn412.setText(btn416.getText());
            btn416.setText("");
            moves++;
        }
        if (btn415.getText().equals("")) {
            btn415.setText(btn416.getText());
            btn416.setText("");
            moves++;
        }
        if (checkWinCondition()) {
            congratulate();
        }
    }//GEN-LAST:event_btn416ActionPerformed

    private void congratulate() {
        running = false;
        String time = lblTime.getText();
        CongratulateForm congratulateForm = new CongratulateForm("" + moves, time);
        congratulateForm.setVisible(true);
        congratulateForm.setLocationRelativeTo(this);
        if (cbboxSize.getSelectedIndex() == 0) {
            for (JButton button : listOf3x3) {
                button.setEnabled(false);
            }
        } else {
            for (JButton button : listOf4x4) {
                button.setEnabled(false);
            }
        }

    }

    private boolean checkWinCondition() {
        lblMove.setText("" + moves);
        if (cbboxSize.getSelectedIndex() == 0) {
            numberList.clear();
            for (int i = 1; i < 9; i++) {
                numberList.add("" + i);
                if (!listOf3x3.get(i - 1).getText().equals(numberList.get(i - 1))) {
                    return false;
                }
            }
            return true;
        } else {
            numberList.clear();
            for (int i = 1; i < 16; i++) {
                numberList.add("" + i);
                if (!listOf4x4.get(i - 1).getText().equals(numberList.get(i - 1))) {
                    return false;
                }
            }
            return true;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonMap;
    private javax.swing.JPanel ButtonMap1;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel Puzzle16Panel;
    private javax.swing.JPanel Puzzle9Panel;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn410;
    private javax.swing.JButton btn411;
    private javax.swing.JButton btn412;
    private javax.swing.JButton btn413;
    private javax.swing.JButton btn414;
    private javax.swing.JButton btn415;
    private javax.swing.JButton btn416;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn48;
    private javax.swing.JButton btn49;
    private javax.swing.JButton btnCheat;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JComboBox<String> cbboxSize;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblMove;
    private javax.swing.JLabel lblMoveCount;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
